# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
r_check_args: --as-cran
matrix:
  include:
    - os: linux
      r: release
    - os: osx
      r: release
