// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// Dq0
double Dq0(double n, double f1, double f2, double g1, double g2, double A);
RcppExport SEXP _PhDyhc_Dq0(SEXP nSEXP, SEXP f1SEXP, SEXP f2SEXP, SEXP g1SEXP, SEXP g2SEXP, SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type f1(f1SEXP);
    Rcpp::traits::input_parameter< double >::type f2(f2SEXP);
    Rcpp::traits::input_parameter< double >::type g1(g1SEXP);
    Rcpp::traits::input_parameter< double >::type g2(g2SEXP);
    Rcpp::traits::input_parameter< double >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(Dq0(n, f1, f2, g1, g2, A));
    return rcpp_result_gen;
END_RCPP
}
// Dq1_1
double Dq1_1(double n, double g1, double A);
RcppExport SEXP _PhDyhc_Dq1_1(SEXP nSEXP, SEXP g1SEXP, SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type g1(g1SEXP);
    Rcpp::traits::input_parameter< double >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(Dq1_1(n, g1, A));
    return rcpp_result_gen;
END_RCPP
}
// Dq2
double Dq2(NumericMatrix tmpaL, double n, double t_bar);
RcppExport SEXP _PhDyhc_Dq2(SEXP tmpaLSEXP, SEXP nSEXP, SEXP t_barSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tmpaL(tmpaLSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type t_bar(t_barSEXP);
    rcpp_result_gen = Rcpp::wrap(Dq2(tmpaL, n, t_bar));
    return rcpp_result_gen;
END_RCPP
}
// delta
double delta(NumericMatrix del_tmpaL, double k, double n);
RcppExport SEXP _PhDyhc_delta(SEXP del_tmpaLSEXP, SEXP kSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type del_tmpaL(del_tmpaLSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(delta(del_tmpaL, k, n));
    return rcpp_result_gen;
END_RCPP
}
// RPD
NumericVector RPD(NumericMatrix x, int n, int m, NumericVector q);
RcppExport SEXP _PhDyhc_RPD(SEXP xSEXP, SEXP nSEXP, SEXP mSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(RPD(x, n, m, q));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PhDyhc_Dq0", (DL_FUNC) &_PhDyhc_Dq0, 6},
    {"_PhDyhc_Dq1_1", (DL_FUNC) &_PhDyhc_Dq1_1, 3},
    {"_PhDyhc_Dq2", (DL_FUNC) &_PhDyhc_Dq2, 3},
    {"_PhDyhc_delta", (DL_FUNC) &_PhDyhc_delta, 3},
    {"_PhDyhc_RPD", (DL_FUNC) &_PhDyhc_RPD, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_PhDyhc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
